### ISSUE TITLE
Partial Overwrite of Nested Properties Fails

### ISSUE THREAD

**Issue by numbnut** [staffanm/layeredconfig#10]
Assuming I defined a PyFile containing my default configuration. This file may look like the following one.

file config_env_bug.conf.py
```
db = {
    "host": "mydbhost.org",
    "port": "9999",
}
```

file config_env_bug.py
```
from layeredconfig import LayeredConfig, PyFile, Environment, Commandline

config = LayeredConfig(PyFile('./config_env_bug.conf.py'), Environment(prefix="MYAPP_"), Commandline())

print("{}".format(config))
```

invocation with cmd arg
```
python config_env_bug.py --db_host=overwrites_port
```
results in
```
'db': {'host': ['overwrites_port']}}
```

invocation with env var
```
export MYAPP_DB_HOST=overwrites_port; python config_env_bug.py
```
results in 
```
'db': {'host': 'overwrites_port'}}
```
which is slightly different but shows the same problem. Defining a hierarchical env var or cmd arg overwrites the whole object and in this case the port number is lost. 

I think this behavior is very inconvenient.

Note: If I recall correctly replacing the PyFile source by a Defaults source fixes this issue.

**Comment by staffanm** [comment]
I'm afraid this is as designed, and due to a pecularity in the API of PyFile when it comes to hierarchies/subsections. Subsections are not created using dicts, like when using a Defaults source. You'll have to create a Subsection object (it'll be automatically available in your .py file, no need to import anything), and then set properties on that object, like this:

```python
db = Subsection() 
db.host = "mydbhost.org"
db.port = "9999"
```

This is sort-of described at http://layeredconfig.readthedocs.io/en/latest/pyfile.html, and is due to the fact that I wanted the setting of config variables in pyfiles to be as similar as possible to reading them in the main application code. Do you think this could be described differently in the docs to be clearer?

**Comment by numbnut** [comment]
Sorry! This was my fault. I'm quite unfamiliar with the Python ini style config including subsections. What I missed completely during reading the doc is the chapter "Embedding configuration in python files", because I looked directly into the "Available sources" section.
While reading the doc again, I think it is quite clear and precise! Sorry for opening this issue!

**Comment by staffanm** [comment]
:+1:
